### ISSUE TITLE
library not supported 

### ISSUE THREAD

**Issue by Saarak101** [Magisk-Modules-Repo/BluetoothLibraryPatcher#11]
this module was working just fine in the past but after the recent update it gives me error while installing and says "library not supported"
please fix this fast my device Bluetooth is not working as it should be 
Device name : samsung j7 nxt (j701f)
android version : oreo 8.1
CPU Architecture : ARMv7-A
Chipset : Samsung exynos 7870
[BluetoothLibPatcher-files.zip](https://github.com/Magisk-Modules-Repo/BluetoothLibraryPatcher/files/5608391/BluetoothLibPatcher-files.zip)

**Comment by 3arthur6** [comment]
Hi
Sorry for the delay, it has been fixed.
