### ISSUE TITLE
library not supported

### ISSUE THREAD

**Issue by agheyew** [Magisk-Modules-Repo/BluetoothLibraryPatcher#13]
I opened this issue here in github becauseI tried to update the magisk module but my bluetooth library isn't supported by the module yet.

I attached the BluetoothLibPatcher-files.tar file that has been created on the main folder of my phone storage. 

my phone is a galaxy a7 2018 (sm-a750fn) and runs android 8.0 Oreo.

[BluetoothLibPatcher-files.tar](https://drive.google.com/file/d/1AR6vfukN0i088qyzfWvRJybTlEltJWRW/view?usp=drivesdk)

**Comment by 3arthur6** [comment]
I just pushed a commit ([a472de2](https://github.com/Magisk-Modules-Repo/BluetoothLibraryPatcher/commit/a472de2bc2aa945bb7798d528a1073a3474104a6)) which should fix your installation error.
Could you tell me if the module fixes now your bt issue?

**Comment by agheyew** [comment]
yeah it works, thank you so much!
