### ISSUE TITLE
Library not supported 

### ISSUE THREAD

**Issue by ahshafin2315** [Magisk-Modules-Repo/BluetoothLibraryPatcher#14]
A library not supported error shows on my installation window. This is probably supposed to happen as I'm on a custom rom called Hades rom built over the port of galaxy note 9 on my galaxy note 8 exynos. Now, I dunno if you're gonna be able to or willing to try and fix this problem but I thought I'd give it a try sending u the files at least and let you see for urself.
Here's the infos if ur not sure what version base this is.
![Screenshot_20210218-164306_Settings](https://user-images.githubusercontent.com/79255498/108347232-7b5f1380-720a-11eb-9c7e-1427c528cbb8.jpg)
![Screenshot_20210218-164408_Settings](https://user-images.githubusercontent.com/79255498/108347238-7dc16d80-720a-11eb-8021-7c02c1f80e93.jpg)

And Here's the tar file generated from installation.
[BluetoothLibPatcher-files.tar](https://drive.google.com/file/d/11OrHb6Qz2wgYYxzUy-uTXYHE8jTO0lV5/view?usp=drivesdk) 
If you need anything else just give me a wave.

**Comment by 3arthur6** [comment]
Sorry for my late
Isn't hades rom already patched out of the box?

**Comment by 3arthur6** [comment]
Just checked, the library is already patched.
