### ISSUE TITLE
Samsung S7, G930FXXS2DRC3, Android 7.0

### ISSUE THREAD

**Issue by mrandroids7** [Magisk-Modules-Repo/BluetoothLibraryPatcher#15]
SM-G930F  Exynos8890, arm, 

[BluetoothLibPatcher-files.tar.zip](https://github.com/Magisk-Modules-Repo/BluetoothLibraryPatcher/files/6005977/BluetoothLibPatcher-files.tar.zip)

**Comment by 3arthur6** [comment]
This installation problem should have been fixed with commit [668ebea](https://github.com/Magisk-Modules-Repo/BluetoothLibraryPatcher/commit/668ebeaf7a2b0c0acaf9780213260362d20e0de1)
And I just modified the patch for your android version.
Did the module fixed your bluetooth issue?

**Comment by mrandroids7** [comment]
Great -- Thank you very much!
Just tested the new BluetoothLibPatcher magisk module on my phone and with my car stereo.
The phone finally keeps bluetooth pairing through reboot & offline/flight mode.

**Comment by 3arthur6** [comment]
Nice to hear!
Thanks a lot for the feedback
