### ISSUE TITLE
Failed to patch library g960FXXUFFUC6

### ISSUE THREAD

**Issue by edzamber** [Magisk-Modules-Repo/BluetoothLibraryPatcher#17]
Hi 

Failed to patch lib in New G960FXCUFFUC6 base updated march 03.31.21 Android 10

Here lib tar 
![Screenshot_20210401-214000](https://user-images.githubusercontent.com/16240238/113345886-65795e00-9333-11eb-91b3-96af7fdcbd30.jpg)
[BluetoothLibPatcher-files.tar.zip](https://github.com/Magisk-Modules-Repo/BluetoothLibraryPatcher/files/6246140/BluetoothLibPatcher-files.tar.zip)

**Comment by 3arthur6** [comment]
Fixed with commit [68b25f2](https://github.com/Magisk-Modules-Repo/BluetoothLibraryPatcher/commit/68b25f2ef6989cbf30836e41f34e1ddab2a041b5)

**Comment by edzamber** [comment]
Many Thanks 👍
