### ISSUE TITLE
S21 Ultra Bluetooth Issue with watch 3

### ISSUE THREAD

**Issue by rehannali** [Magisk-Modules-Repo/BluetoothLibraryPatcher#18]
i install twrp on my S21 Ultra and flash zip from it. It show me, Gear watch fix not needed/already applied in TWRP etc and i'm unable to pair my watch 3 with my S21 Ultra.

Any solution to this problem?

**Comment by rehannali** [comment]
I tried to execute commands you mentioned and still it won't work. I also didn't find any Bluetooth patch file in my main directory after flashing it. It keep disconnecting bluetooth from my watch and when i tried to connect it manually, it won't connect either.

**Comment by 3arthur6** [comment]
Hi
Can you connect any other bluetooth device and keep it paired or the problem is only with your gear?

**Comment by rehannali** [comment]
@3arthur6 i only have problem with my watch 3 and it is fixed now with patched files made for snapdragon device.

**Comment by 3arthur6** [comment]
Nice!
Patched files for snapdragon?

**Comment by cooljoet** [comment]
heya, ive got a galaxy watch and a s21. tried looking on official TWRP app and don't think s21 is supported :S if someone gives a rough guide ill do a youtube vid to hopefully help some other people out and guide them in the right direction.
