### ISSUE TITLE
Samsung Note5 SM-N920C İnstalling Problem

### ISSUE THREAD

**Issue by adigeefe** [Magisk-Modules-Repo/BluetoothLibraryPatcher#2]
I have Note5 I want to install this patch but TWRP&Magisk Manager says "Updater process ended with ERROR: 123 Error installing zip file 'sdcard/Download/Bluethoot_Library_Patcher-v1.9.zip" what should ı do (Magisk Manager also says like this)

**Comment by 3arthur6** [comment]
Sorry for my late!
I'm pretty sure this patch isn't relevant with a Note5.
What is your bluetooth issue?

**Comment by kasraeii** [comment]
I have same problem. Could you please add android 7.0 support?!

**Comment by 3arthur6** [comment]
The latest release could handle Android 7.0. Give it a new try and send a feedback please.

**Comment by kasraeii** [comment]
Hey! Sorry for late
I've tried v2 and installed it successfully but I couldn't control Bluetooth anymore; so I had to revert it.
In the new version v2.2 I got some errors.

**Comment by 3arthur6** [comment]
> Hey! Sorry for late
> I've tried v2 and installed it successfully but I couldn't control Bluetooth anymore; so I had to revert it.
> In the new version v2.2 I got some errors.

Hi
Can you try this version : [BluetoothLibraryPatcher_magisk.zip](https://github.com/Magisk-Modules-Repo/BluetoothLibraryPatcher/files/5599072/BluetoothLibraryPatcher_magisk.zip)

**Comment by kasraeii** [comment]
Hey Arthur! I've given a try and it failed again. Here is the log:

**Comment by 3arthur6** [comment]
> Hey Arthur! I've given a try and it failed again. 

Hi!
Can you give more info?
Your log seems to be a quote of my previous answer..

**Comment by kasraeii** [comment]
hi Arthur
in the last email, I've sent the install log as an attachment. check it
out. here is a link to the attachment if you can't find it:
magisk_install_log_2020-11-26T02:26:07Z.log -1KB
<https://mail.google.com/mail/u/1?ui=2&ik=4ce1d7744a&attid=0.1&permmsgid=msg-a:r3630083732328940008&th=17601a94cdc8bc39&view=att&disp=safe&realattid=17601a599a330ab5c871>

**Comment by 3arthur6** [comment]
Hi
I can't acces the file..
Can you upload it elsewhere?

**Comment by kasraeii** [comment]
Yea sure. Here it is:
https://gofile.io/d/dFUV7H

**Comment by 3arthur6** [comment]
My bad sorry..!
Try this fixed one : [BluetoothLibraryPatcher_magisk.zip](https://github.com/Magisk-Modules-Repo/BluetoothLibraryPatcher/files/5610449/BluetoothLibraryPatcher_magisk.zip)

**Comment by kasraeii** [comment]
OK, IT WORKED. Bluetooth disconnect on reboot which is not a big deal BUT
as I turn on airplane mode; It turns Bluetooth off but I can turn it on
again and search for nearby devices. (paired devices isn't available)

**Comment by 3arthur6** [comment]
> OK, IT WORKED. Bluetooth disconnect on reboot which is not a big deal BUT
> as I turn on airplane mode; It turns Bluetooth off but I can turn it on
> again and search for nearby devices. (paired devices isn't available)

Not sure to understand😅
You confirm your paired bluetooth devices are kept after a reboot with this version?

**Comment by kasraeii** [comment]
Nope! I checked it just now and my paired devices are gone
It still turns bluetooth off on airplane mode switch on. Can you do
something with it?

**Comment by 3arthur6** [comment]
> Nope! I checked it just now and my paired devices are gone
> It still turns bluetooth off on airplane mode switch on. Can you do
> something with it?

Hey!
Humm... At this point I'm not sure I will be able to support your device..
But I can investigate a bit more. Could you send me the file /data/misc/bluedroiddump/subBuffer.log if it exists on your device?

**Comment by kasraeii** [comment]
Sure! Tnx.
