### ISSUE TITLE
Messing up bluetooth on s10e with Android 11

### ISSUE THREAD

**Issue by Kiblyn11** [Magisk-Modules-Repo/BluetoothLibraryPatcher#21]
Version: 2.2.3
Issue: When trying to enable bluetooth, it stays disabled
Logcat: `BluetoothServiceJni: hal_util_load_bt_library: failed to load Bluetooth library, error=dlopen failed: cannot locate symbol "_ZN6google8protobuf8internal23empty_string_once_init_E" referenced by "/system/lib64/libbluetooth.so"`
Magisk: No special issue in logs

**Comment by 3arthur6** [comment]
Hi
Whoops
Could you attach your /system/build.prop and /system/lib64/libbluetooth.so files here?

**Comment by Kiblyn11** [comment]
Sure,

libbluetooth: https://drop.infini.fr/r/skCU8_oCMe#9x6qrKBtKCmQDYT+cThjtbIWFnYQ7/0yiqWIQiAS9MY=
build.prop: https://drop.infini.fr/r/52sSMtk3oF#wToJp0YVOMd3w+TBknGZfHCLJB0CETv59WeTk3mkea8=

**Comment by 3arthur6** [comment]
At this point I can't find that is causing this.. Your bluetooth library seems ready to be patched.
Could you try to replace it manually (make a backup of the original!) with the one I attached and see what happen?

[libbluetooth-fixed.zip](https://github.com/Magisk-Modules-Repo/BluetoothLibraryPatcher/files/6771518/libbluetooth-fixed.zip)

**Comment by Kiblyn11** [comment]
It is working, I just thought about something.
I updated from Android 10 to Android 11 without reinstalling the module.
It seems it was the issue as I just reinstalled it and everything is working !

Thanks and sorry for bothering.
