### ISSUE TITLE
BluetoothLibPatcher-files.tar

### ISSUE THREAD

**Issue by OutbakjakX007** [Magisk-Modules-Repo/BluetoothLibraryPatcher#22]
[BluetoothLibPatcher-files.tar - 
Android Q unsupported device]
(https://drive.google.com/file/d/1XLj-Hz9RFwBl2qPFrhp-sRPjo0w_bEzg/view?usp=drivesdk)

**Comment by 3arthur6** [comment]
Hi
It's a false positive, your rom seems prepatched
