### ISSUE TITLE
Confusion regarding 'wearables pairing issue'

### ISSUE THREAD

**Issue by joostvhts** [Magisk-Modules-Repo/BluetoothLibraryPatcher#23]
Hi,

Thx for your efforts with this module! It successfully helped me pair my new Galaxy Watch3 to my S20FE.

However I was confused by the bit in the description regarding the commands that needed to be run. Could you please clarify the instruction, for example replacing

> To fix Galaxy Wearable pairing issue, as the modifcations aren't applicable through Magisk :
> 
> Either go to XDA twrp flashable zip.
> 
> /!\ S21 serie owner need the twrp zip (for vendor partition resizing), terminal commands below could brick your device /!\
> 
> Or you can directly execute these commands from a terminal app, one line after another, then reboot :
> 
> `su`
> `mount -o remount,rw /vendor`
> `i=\``grep -lr 'security.wsm' /vendor/etc/vintf`` && [ ! -z $i ] && [ $i != *.bak ] && cp --preserve=all $i $i.bak && sed -i '/<.*security.wsm.*/,/<hal format="hidl">/d' $i`
> `mount -o remount,ro /vendor`

by something like:

> Due to limitations in Magisk, a manual step is required to fix pairing issues with Galaxy Watch devices. After installing the Magisk module, use a command line (like Terminal Emulator or Termux) to run the following commands, then reboot:
> 
> *Beware! /!\ Owners of the S21 series cannot use these commands (meant for resizing the vendor partition) and must instead use the zip to flash using TWRP. The commands below could brick your device /!\*
> 
> `su`
> `mount -o remount,rw /vendor`
> `i=\``grep -lr 'security.wsm' /vendor/etc/vintf`` && [ ! -z $i ] && [ $i != *.bak ] && cp --preserve=all $i $i.bak && sed -i '/<.*security.wsm.*/,/<hal format="hidl">/d' $i`
> `mount -o remount,ro /vendor`
> 
> Alternatively, instead of installing the Magisk module and running the commands, flash the zip file (BluetoothLibraryPatcher_X.X.X.zip​) meant for TWRP recovery found on [XDA](https://forum.xda-developers.com/t/bluetoothlibrarypatcher-fix-bluetooth-pairings-loss-android-11-10-pie-oreo-nougat.4017735/) under 'Links'.

(and maybe put something similar in the Magisk module's description and XDA thread?)

**Comment by 3arthur6** [comment]
English and pedagogy are clearly not my strengths.
I will merge this, thanks!

**Comment by joostvhts** [comment]
> English and pedagogy are clearly not my strengths.
> I will merge this, thanks!

Thanks! It was good enough to help me out a lot, I just felt like this might help other people benefit from your work too :)
