### ISSUE TITLE
How to download module?

### ISSUE THREAD

**Issue by Luix333** [Magisk-Modules-Repo/BluetoothLibraryPatcher#27]
First of all, thank you for all the hard work!

I would like to know how to download the ZIP module since I believe the magisk repo is no longer accessible from the magisk manager app.

**Comment by rahulary** [comment]
Even I have the same problem

**Comment by 3arthur6** [comment]
Hi
I just added a release from latest sources on github, I will keep publish releases this way.

**Comment by rahulary** [comment]
Thanks man
