### ISSUE TITLE
twrp vendor 

### ISSUE THREAD

**Issue by david-lev** [Magisk-Modules-Repo/BluetoothLibraryPatcher#28]
Hi, i just want to find out why i need to flash the BluetoothLibraryPatcher_twrp_XXX.zip in my S21 from twrp recovery? 
Why is it not possible to create  a simple module that will [replace](https://topjohnwu.github.io/Magisk/details.html#:~:text=if%20you%20want%20to%20replace%20files%20in%20%2Fvendor%20or%20%2Fproduct%2C%20please%20place%20them%20under%20%24modpath%2Fsystem%2Fvendor%20or%20%24modpath%2Fsystem%2Fproduct.%20magisk%20will%20transparently%20handle%20both%20cases%2C%20whether%20vendor%20or%20product%20is%20a%20separate%20partition%20or%20not) the file from vendor partition? (/vendor/etc/vintf/security.wsm)

**Comment by 3arthur6** [comment]
Hi!
If it was possible I would have choose this option.
But sadly Android loads it to early for Magisk to handle it.
In addition I don't own samsung gear so I can't investigate properly to search for another workaround.
