### ISSUE TITLE
Unable to Write S21 Ultra Snapdragon

### ISSUE THREAD

**Issue by rehannali** [Magisk-Modules-Repo/BluetoothLibraryPatcher#29]
Hi, i tried module with magisk, don't work for me and i tried twrp file with Franco Kernel and ex kernel app to flash zip file. I'm unable to boot with twrp and decryption. I tried this way because i don't have TWRP.
I got error of read only partition while flashing twrp file and got success message using magisk but in both cases have same result.
I'm unable to pair my watch 3 to my phone. Any help regarding this issue?

**Comment by 3arthur6** [comment]
Hi!
Did you try the terminal commands?
`su
mount -o remount,rw /vendor
i=`grep -lr 'security.wsm' /vendor/etc/vintf` && [ ! -z $i ] && [ $i != *.bak ] && cp --preserve=all $i $i.bak && sed -i '/<.*security.wsm.*/,/<hal format="hidl">/d' $i
mount -o remount,ro /vendor`

**Comment by rehannali** [comment]
Hi. Issue resolved. I tried without twrp and 8t won't work. After installation of twrp, everything works fine.
