### ISSUE TITLE
Samsung Galaxy A6+ SM-A605FN İnstalling Problem

### ISSUE THREAD

**Issue by EvRacoon** [Magisk-Modules-Repo/BluetoothLibraryPatcher#6]
It doesn't install on my phone. Android 10 I found version 1.4 it says no bluetooth.so

**Comment by 3arthur6** [comment]
Hi
Could you try again? It have been fixed for some devices so maybe yours too.
If not could you give more info about the error?

**Comment by EvRacoon** [comment]
> Hi
> Could you try again? It have been fixed for some devices so maybe yours too.
> If not could you give more info about the error?

Hi, thanks for the update. The September 21 update was able to install. Thank you very much for your work.
