### ISSUE TITLE
三星G977NKSU4DTJ8安装2.2版本失败！

### ISSUE THREAD

**Issue by tomatolei** [Magisk-Modules-Repo/BluetoothLibraryPatcher#7]
三星S10 5G最新版 G977NKSU4DTJ8，安装2.2的失败，下面提供了截图和文件
Samsung S105G latest version g977nksu4dtj8 failed to install 2.2. The screenshots and files are provided below

安装截图Installation screenshot 
https://mega.nz/file/28ATxKRa#D4HFfUc_ahB5MhbtnWhTyDKw01EEWm4GbFNO8ioF4jM

原版文件G977NKSU4DTJ8 Original unmodified Bluetooth file libbluetooth.so
https://mega.nz/file/r8RnkAAA#ypp7H010P9vA8Sppmr-gfEnkjVRfZx5Iqfs8ZmzHvi0

**Comment by 3arthur6** [comment]
Hey
Could you upload the full BluetoothLibPatcher-files.tar file please?
Sorry but I need more informations to find how it fails.
Install the module again and this file will be created at the internal storage of your phone.

**Comment by tomatolei** [comment]
BluetoothLibPatcher-files.tar
https://mega.nz/file/P0xh1brY#FIXuWy82vGReL5zG2tzRQv6P9IYDwd37Tymh-nVAIwI

**Comment by 3arthur6** [comment]
> BluetoothLibPatcher-files.tar
> https://mega.nz/file/P0xh1brY#FIXuWy82vGReL5zG2tzRQv6P9IYDwd37Tymh-nVAIwI

Humm this file does not appear to be the right one.
Install the module then look at the root of your main storage for BluetoothLibPatcher-files.tar

**Comment by tomatolei** [comment]
> > BluetoothLibPatcher-files.tar
> > https://mega.nz/file/P0xh1brY#FIXuWy82vGReL5zG2tzRQv6P9IYDwd37Tymh-nVAIwI
> 
> Humm this file does not appear to be the right one.
> Install the module then look at the root of your main storage for BluetoothLibPatcher-files.tar

I re installed the official firmware, and after root installed magickv21, I found that the Bluetooth file could be successfully patched!
Maybe I modified the model before, resulting in the failure of cracking!
Thank you for your help!

**Comment by 3arthur6** [comment]
OK perfect! Yeah depending on which kind of modification it may have affected the patch.
Thanks for report
