### ISSUE TITLE
Module with persistant Icon in Magisk Manager

### ISSUE THREAD

**Issue by kinesight** [Magisk-Modules-Repo/BluetoothLibraryPatcher#8]
![Screenshot_20201112-150241](https://user-images.githubusercontent.com/58188282/98951080-7ea77c80-2502-11eb-8865-94de7c512a60.jpg)

Not sure if this is an issue with Magisk or with the module but since I updated the latest version of the module, there was this icon which stayed behind the BTLP module. 

- I rebooted and it was still there
- I removed the module and rebooted and it stayed there
- I disabled the module then rebooted then I tapped to remove it and only then was it removed from Magisk

I did reinstall after that and still the same thing happens.

This is still happening with the latest version of the module. @3arthur6

**Comment by 3arthur6** [comment]
Hey
Thanks for report it!
Reinstall the module then reboot and it should be fixed with last commit.

**Comment by kinesight** [comment]
> Hey
> Thanks for report it!
> Reinstall the module then reboot and it should be fixed with last commit.

I just updated from 2.2.1 to 2.2.2 and it seems to be fine now. No icon in background.
