### ISSUE TITLE
Samsung SM-N9600 Note9 OneUI 2.5 N9600ZCU5FTJ8 can not patch

### ISSUE THREAD

**Issue by tomatolei** [Magisk-Modules-Repo/BluetoothLibraryPatcher#9]
Samsung SM-N9600 Note9 OneUI 2.5 N9600ZCU5FTJ8 can not patch
BluetoothLibPatcher-files.tar is upload to mega
https://mega.nz/file/GlpinDjQ#nZzw2R8dT0ODaSjSli2oloEpNMWJyTrs88DtSRqmnbo

**Comment by 3arthur6** [comment]
Hey
Thanks for report!
Just pushed a fix. Try again it should be ok.

**Comment by 3arthur6** [comment]
Hey
Isn't it fixed?

**Comment by tomatolei** [comment]
thank you,it is works!
